version: "3.9"

services:
  # MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  # Angular web service
  web:
    build: demo3
    ports:
      - 4200:4200
    volumes:
      - ./demo3:/app/client
    depends_on:
      - mongo_db

  # Node API service
  api:
    build: demo1
    ports:
      - 4000:8000
    environment:
      PORT: 8000
      MONGO_URI: mongodb://mongo_db:27017/
      DB_NAME: my_db
    volumes:
      - ./demo1:/app/api
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
